INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('natrij-fluorid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('heksetidin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('polivinil-pirolidon + natrij-hijalurat + gliciretinična kiselina');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ranitidin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('famotidin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('omeprazol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('pantoprazol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('lanzoprazol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('esomeprazol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('bizmut oksid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('atropin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('hioscin-butilbromid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('metoklopramid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ondansetron');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('granisetron');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('palonosetron');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('netupitant + palonozetron');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('aprepitant');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ursodeoksikolna kiselina');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('laktuloza');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('fidaksomicin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('aktivni (medicinski) ugljen');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('natrij-klorid + kalij-klorid + natrij-citrat');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('sulfasalazin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('enzimi gušterače (visoko dozirani)');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('inzulin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('inzulin lispro');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('inzulin aspart');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('inzulin glulizin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('inzulin human');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('inzulin degludek + inzulin aspart');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('inzulin glargin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('inzulin detemir');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('inzulin glargin + liksisenatid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('metformin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('glibenklamid-mikrokrist.');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('gliklazid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('glimepirid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('metformin + glibenklamid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('pioglitazon + metformin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('vildagliptin + metformin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('pioglitazon');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('vildagliptin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('eksenatid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('liksisenatid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('dulaglutid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('semaglutid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('repaglinid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('dihidrotahisterol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('kalcitriol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('kolekalciferol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('vitamini B kompleksa');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('tokoferol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('kalcij-glukobionat');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('kalcij-karbonat');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('kalij-klorid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('kalijev citrat');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('kalij-citrat + kalij-hidrogenkarbonat');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('levokarnitin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('imigluceraza');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('agalzidaza alfa');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('agalzidaza beta');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('laronidaza');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('alglukozidaza alfa');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('galsulfaza');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('idursulfaza');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('velagluceraza alfa');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('elosulfaza alfa');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('cerliponaza alfa');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('nitizinon');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('teduglutid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('eliglustat');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('migalastat');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('varfarin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('heparin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('heparinnatrij');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('antitrombin III');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('dalteparin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('enoksaparin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('nadroparin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('klopidogrel');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('acetilsalicilna kiselina');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('dipiridamol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('iloprost');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('eptifibatid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('prasugrel');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('tikagrelor');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('alteplaza');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('dabigatran eteksilat');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('rivaroksaban');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('apiksaban');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('fondaparinuks');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('aminokapronska kiselina');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('traneksamična kiselina');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('aprotinin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('fitomenadion');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('fibrinogen (humani)');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ljudski fibrinogen, ljudski trombin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ljudski protrombinski kompleks');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('rekombinantni čimbenik VIIIFc (efmoroktokog alfa)');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('rekombinantni čimbenik VIII (damoktokog alfa pegol)');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('rekombinantni čimbenik VIII (rurioktokog alfa pegol)');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('rekombinantni čimbenik VIII (turoktokog alfa pegol)');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('rekombinantni čimbenik VIII (turoktokog alfa)');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('čimbenik VIII');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('rekombinantni čimbenik VIII (oktokog alfa)');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('rekombinantni čimbenik VIII (moroktokog alfa)');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('rekombinantni čimbenik VIII (simoktokog alfa)');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('aktivirani koncentrat čimbenika protrombinskog kompleksa');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('čimbenik IX');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('rekombinantni čimbenik IXFc (eftrenonakog alfa)');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('rekombinantni humani faktor IX (nonakog beta pegol)');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('koagulacijski faktor VIII, ljudski, von Willebrandov faktor, ljudski');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('konc. čimbenik VIII s von Willebrandovim čimbenikom');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('čimbenik ugrušavanja krvi XIII');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('aktivirani rekombinantni čimbenik VII A');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('rekombinantni čimbenik IX (nonakog alfa)');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('romiplostim');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('eltrombopag');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('emicizumab');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('željezo II -fumarat');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('željezo karboksimaltoza');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('željezo III-oksid saharat');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('željezo III-sorbitol glukonska kiselina');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('željezov (III) izomaltozid 1000');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('cijanokobalamin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('folatna kiselina');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('eritropoetin theta');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('epoetin alfa');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('epoetin beta');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('eritropoetin zeta');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('darbepoetin alfa');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('metoksi polietilenglikol-epoetin beta');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ljudski albumin 5%');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ljudski albumin 20%');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('proteini ljudske plazme');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('dekstran 40');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('želatina');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('hidroksietil škrob');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('hidroksietil škrob (poli-o-2-hidroksietil škrob)');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('infuzije aminokiselina (N (2)-L-alanin-L-glutamin)');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('otopine masti i masnih kiselina');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('glukoza');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('glukoza+otopina aminokiselina s elektrolitima+masna emulzija');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('emulzija lipida + aminokiselina + glukoza + kalcij- klorid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('emulzija lipida + aminokiselina + glukoza + kalcij-klorid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('glukoza + otopina aminokiselina + emulzija lipida');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('glukoza + otopina aminokiselina s elektrolitima + emulzija lipida');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('infuzije aminokiselina');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('glukoza+otopina aminokiselina s elektrolitima+emulzija lipida');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('emulzija lipida + aminokiselina + glukoza');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('natrij-klorid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('natrij-klorid + kalij-klorid + magnezij-klorid heksahidrat + kalcij-klorid dihidrat + natrij-acetat trihidrat + L-malatna kiselina');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('natrij-klorid + kalij-klorid + magnezij-klorid heksahidrat + natrij-acetat trihidrat');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('natrij-klorid + kalij-klorid + magnezij-klorid heksahidrat + natrij-acetat-trihidrat + natrij-glukonat');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('glukoza + natrij-klorid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('manitol + natrij-klorid + natrij-acetat');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('manitol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('otopine za ispiranje mokraćnog mjehura');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('otopina za ispiranje kod endoskopskih pretraga i operativnih zahvata');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('otopina za ispiranje');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('natrij-hidrogenkarbonat');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('magnezij-sulfat');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('kalcij-klorid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('natrij-klorid + kalcij-klorid + kalij-klorid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('natrij-klorid + natrij-acetat + natrij-laktat + kalcij-klorid + kalij-klorid + magnezij klorid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('natrij-klorid + kalij- klorid + kalcij-klorid-dihidrat + natrij-laktat');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('natrij-klorid + kalij-klorid + kalcij-klorid-dihidrat + natrij-laktat');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ikatibant');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('konestat alfa');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('metildigoksin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('lidokain');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('propafenon');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('amjodaron');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('etiladrianol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('noradrenalin (norepinefrin)');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('dopamin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('dobutamin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('adrenalin (epinefrin)');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('levosimendan');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('gliceriltrinitrat');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('izosorbid-dinitrat');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('izosorbid-5-mononitrat');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('izosorbid mononitrat');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('alprostadil');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('trimetazidin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('l-metildopa');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('moksonidin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('doksazosin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('urapidil');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('diazoksid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('minoksidil');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('nitroprusid-natrij');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('bosentan');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ambrisentan');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('klortalidon');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('indapamid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('furosemid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('fentolamin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('propranolol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('metoprolol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('atenolol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('bisoprolol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('nebivolol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('karvedilol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('amlodipin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('nifedipin srednje dugodjelujući');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('nifedipin dugodjelujući');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('nimodipin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('lacidipin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('lerkanidipin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('verapamil');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('enalapril');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('lizinopril');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('perindopril');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ramipril');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('cilazapril');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('enalapril + hidroklorotiazid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('lizinopril + hidroklorotiazid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('perindopril + indapamid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ramipril + hidroklorotiazid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('cilazapril + hidroklorotiazid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('perindopril + amlodipin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ramipril + amlodipin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('perindopril + indapamid + amlodipin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ramipril + amlodipin + hidroklorotiazid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('losartan');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('valsartan');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('kandesartan');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('telmisartan');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('losartan + hidroklorotiazid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('valsartan + hidroklorotiazid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('kandesartan + hidroklorotiazid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('telmisartan + hidroklorotiazid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('amlodipin + valsartan');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('amlodipin + valsartan + hidroklorotiazid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('simvastatin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('fluvastatin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('atorvastatin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('rosuvastatin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('fenofibrat');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('kolestiramin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ezetimib');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('evolokumab');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('alirokumab');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('rosuvastatin + ezetimib');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('amlodipin + atorvastatin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('rosuvastatin + amlodipin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('rosuvastatin + perindopril + indapamid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ketokonazol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('terbinafin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('metoksalen (metoksipsoralen)');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('acitretin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('fusidatna kiselina');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('kloramfenikol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('mupirocin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('sulfadiazin-srebro');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('alklometazon');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('betametazon');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('betametazon + gentamicin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('betametazon + salicilna kiselina');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('klorheksidin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('povidon-jod');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('oktenidin + fenoksietanol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('etanol + bifenilol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('izopropanol + butandiol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('izopropanol + etanol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('nistatin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('metilergometrin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ergometrin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('dinoproston');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('karboprost');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('levonorgestrel');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('fenoterol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('atosiban');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('testosteron');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('estradiol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('medroksiprogesteron');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('progesteron');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('koriogonadotropin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('menotropin (FSH+LH)');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('folitropin alfa');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('folitropin beta');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('korifolitropin alfa');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('folitropin delta');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('folitropin alfa + lutropin alfa');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('klomifen');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ciproteron-acetat');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ciproteron-acetat + etinilestradiol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('danazol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('raloksifen');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('oksibutinin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('solifenacin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('trospij');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('darifenacin hidrobromid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('mirabegron');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('desfesoterodin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('sildenafil');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('tamsulozin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('silodosin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('dutasterid + tamsulozin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('solifenacin + tamsulozin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('finasterid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('tetrakozaktid (tetracosactrin)');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('tirotropin alfa');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('somatropin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('pegvisomant');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('dezmopresin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('terlipresin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('oksitocin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('gonadorelin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('oktreotid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ganireliks');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('cetroreliks');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('fludrokortizon');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('deksametazon');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('metilprednizolon-sukcinat-natrij');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('metilprednizolon-acetat');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('prednizon');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('hidrokortizon');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('levotiroksin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('liotironin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('propiltiouracil');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('tiamazol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('glukagon');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('teriparatid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('sinakalcet');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('parikalcitol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('etelkalcetid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('doksiciklin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('tigeciklin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ampicilin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('amoksicilin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('benzilpenicilin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('fenoksimetilpenicilin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('benzatin benzilpenicilin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('prokain benzilpenicilin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('benzilpenicilin prokainpenicilin (depo-bipenicilin)');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('flukloksacilin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ampicilin + sulbaktam');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('amoksicilin + klavulanska kiselina');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('piperacilin + tazobaktam');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('cefaleksin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('cefazolin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('cefuroksim');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('cefotaksim');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ceftazidim');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ceftriakson');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('cefiksim');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('cefpodoksim');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ceftazidim + avibaktam');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('cefepim');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('meropenem');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ertapenem');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('imipenem + cilastatin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ceftarolin fosamil');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ceftolozan + tazobaktam');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('trimetoprim');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('sulfametoksazol + trimetoprim');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('eritromicin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('klaritromicin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('azitromicin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('klindamicin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('streptomicin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('tobramicin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('gentamicin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('amikacin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('netilmicin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ofloksacin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ciprofloksacin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('pefloksacin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('norfloksacin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('levofloksacin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('moksifloksacin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('vankomicin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('teikoplanin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('kolistimetat-natrij');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('kolistin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('metronidazol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('nitrofurantoin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('fosfomicin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('linezolid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('amfotericin B');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('flukonazol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('itrakonazol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('vorikonazol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('posakonazol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('izavukonazol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('flucitozin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('kaspofungin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('mikafungin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('anidulafungin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('aminosalicilna kiselina (PAS)');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('cikloserin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('rifampicin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('rifabutin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('izoniazid + piridoksin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('protionamid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('pirazinamid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('etambutol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('aciklovir');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ganciklovir');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('valganciklovir');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ritonavir');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('darunavir');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('zidovudin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('lamivudin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('abakavir');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('tenofovir');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('entekavir');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('telbivudin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('tenofovir alafenamid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('nevirapin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('efavirenz');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('doravirin + lamivudin + tenofovir dizoproksil');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('zanamivir');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('oseltamivir');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ribavirin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ledipasvir + sofosbuvir');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('sofosbuvir + velpatasvir + voksilaprevir');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('glekaprevir + pibrentasvir');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('abakavir + lamivudin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('emtricitabin + tenofovir');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('efavirenz + emtricitabin + tenofovir dizoproksil');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('lopinavir + ritonavir');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('dolutegravir + abakavir + lamivudin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('darunavir + kobicistat');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('emtricitabin + tenofovir alafenamid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('elvitegravir + kobicistat + emtricitabin + tenofovir alafenamid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('emtricitabin + rilpivirin + tenofovir alafenamid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('biktegravir + emtricitabin + tenofovir alafenamid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('dolutegravir + rilpivirin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('dolutegravir + lamivudin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('raltegravir');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('dolutegravir');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('letermovir');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('elbasvir + grazoprevir');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('sofosbuvir + velpatasvir');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('imunoglobulin-antitoksin protiv otrova zmija (purificiran i koncentriran)');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('imunoglobulin-antitoksin botulinum');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('imunoglobulin-antitoksin protiv plinske gangrene');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('imunoglobulin-antitoksin protiv otrova pauka (crna udovica)');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('imunoglobulin, ljudski');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('imunoglobulin za subkutanu primjenu');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('imunoglobulin za intraven. primjenu 7 S');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('imunoglobulin za intraven. primjenu7 S');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('imunoglobulin za intraven. primjenu 5 S');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('imunoglobulin anti-D-(Rho) (ljudski)');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('imunoglobulin antitetanus - TIG (ljudski)');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('imunoglobulin antitetanus hiperimuni (5000i.j.)');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('imunoglobulin Varicella/zoster');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('imunoglobulin anti-HBs (ljudski)');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('imunoglobulin protiv hepatitisa B (ljudski)');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('imunoglobulin protiv bjesnoće (ljudski)');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('hiperimuni anti-citomegalo virus (ljudski)');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('imunoglobulin protiv krpeljnog meningoencefalitisa (ljudski)');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('palivizumab');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('cjepivo protiv Haemophilusa influenzae tipa B');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('cjepivo protiv Haemophilus influenzae tipB');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('cjepivo protiv meningokokne bolesti, tetravalentno (A, C, W-135, Y)');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('cjepivo protiv meningokoka grupe B (rDNK, komponentno, adsorbirano)');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('cjepivo protiv difterije, tetanusa i pertusisa');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('cjepivo protiv pneumokokne bolesti');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('cjepivo protiv pneumokoka, polisaharidno, konjugirano, 13-valentno, adsorbirano');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('cjepivo protiv pneumokoka, polisaharidno, konjugirano, adsorbirano');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('tetanus anatoksin (ANA-TE)');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('tetanus anatoksin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('cjepivo protiv difterije-tetanusa pro adultis (ANA-DI-TE pro adultis)');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('cjepivo protiv difterije i tetanusa');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('cjepivo (BCG) protiv tuberkuloze, živo atenuirano');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('BCG-cjepivo protiv tuberkuloze-živo, atenuirano');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('cjepivo protiv tifusa, polisaharidno');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('cjepivo protiv gripe');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('cjepivo protiv hepatitisa B');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('cjepivo protiv hepatitisa B (rDNA)');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('cjepivo protiv hepatitisa A');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('cjepivo protiv morbila (MO)');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('cjepivo protiv ospica');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('cjepivo protiv morbila-parotitisa-rubele (MO-PA-RU)');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('cjepivo protiv ospica, mumpsa i rubele');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('cjepivo protiv morbila-parotitisa-rubele, živo');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('cjepivo protiv parotitisa (PA)');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('cjepivo protiv dječje paralize, inaktivirano');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('cjepivo protiv bjesnoće');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('monovalentno cjepivo protiv rotavirusa');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('5- valentno cjepivo protiv rotavirusa');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('cjepivo protiv rubele (RU )');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('cjepivo protiv rubele');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('cjepivo protiv varičela');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('cjepivo protiv humanog papilomavirusa');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('2- valentno cjepivo protiv humanog papilomavirusa');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('9-valentno cjepivo protiv humanog papilomavirusa (rekombinantno, adsorbirano)');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('cjepivo protiv difterije, tetanusa i dječje paralize (Td-IPV)');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('cjepivo protiv difterije, tetanusa, pertusisa, dječje paralize i Haemophilusa influenzae tipa B');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('cjepivo protiv difterije, tetanusa-DT, pertusisa-(acelularno), poliomijelitisa-IPV (inaktivirano), adsorbirano i Haemophilus influenzae tip b (konjugirano)');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('cjepivo protiv difterije, tetanusa, pertusisa (acelularno), dječje paralize (inaktivirano),H. influenzae tipa B i hepatitisa B');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ciklofosfamid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('klorambucil');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('melfalan');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('klormetin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ifosfamid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('bendamustin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('busulfan');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('karmustin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('lomustin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('temozolomid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('dakarbazin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('metotreksat');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('pemetreksed');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('merkaptopurin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('tioguanin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('kladribin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('fludarabin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('klofarabin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('citarabin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('5-fluorouracil');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('gemcitabin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('kapecitabin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('azacitidin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('trifluridin + tipiracil');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('vinblastin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('vinkristin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('vindesin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('vinorelbin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('etopozid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('paklitaksel');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('paklitaksel (nab)');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('docetaksel');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('kabazitaksel');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('trabektedin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('daktinomicin (aktinomicin-D)');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('doksorubicin liposomalni');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('doksorubicin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('daunorubicin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('epirubicin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('idarubicin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('mitoksantron');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('piksantron');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('bleomicin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('mitomicin-D');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('cisplatin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('karboplatin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('oksaliplatin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('prokarbazin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('rituksimab');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('trastuzumab');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('cetuksimab');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('bevacizumab');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('panitumumab');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('brentuksimab vedotin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('pertuzumab');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('trastuzumab emtanzin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('obinutuzumab');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('dinutuksimab beta');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('nivolumab');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('pembrolizumab');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ramucirumab');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('daratumumab');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('durvalumab');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('atezolizumab');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('imatinib');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('gefitinib');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('erlotinib');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('sunitinib');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('sorafenib');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('dasatinib');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('lapatinib');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('nilotinib');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('temsirolimus');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('everolimus');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('pazopanib');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('vandetanib');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('afatinib');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('bosutinib');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('vemurafenib');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('krizotinib');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('aksitinib');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ruksolitinib');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('regorafenib');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('dabrafenib');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('trametinib');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ibrutinib');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('nintedanib');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('palbociklib');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('osimertinib');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('alektinib');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('kobimetinib');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('midostaurin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ribociklib');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('brigatinib');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('lorlatinib');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('abemaciklib');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('amsakrin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('L-asparaginaza');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('hidroksiureja');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('estramustin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('topotekan');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('irinotekan');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('pegaspergaza');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('bortezomib');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('anagrelid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('aflibercept');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('karfilzomib');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('olaparib');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('idelalisib');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('iksazomib');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('venetoklaks');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('tisagenlekleucel');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('megestrol-acetat');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('buserelin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('leuprorelin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('goserelin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('triptorelin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('tamoksifen');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('fulvestrant');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('flutamid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('nilutamid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('bikalutamid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('enzalutamid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('apalutamid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('anastrozol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('letrozol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('eksemestan');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('abirateron');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('filgrastim');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('molgramostim');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('lenograstim');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('pegfilgrastim');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('lipegfilgrastim');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('interferon alfa-2a');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('interferon beta-1a');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('interferon beta-1b');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('peginterferon alfa-2a');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('peginterferon beta-1a');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('BCG vaccinum');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('glatiramer acetat (kopolimer-1)');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('glatirameracetat');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('pleriksafor');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('elapegademaza-lvlr');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('muromonab (CD3)');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('imunoglobulin-antilimfocitniALG');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('imunoglobulin protiv T limfocita, kunićiji za humanu primj.');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('kunićji imunoglobulin protiv timocita, za ljude');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('mikofenolat mofetil');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('mikofenolat-natrij');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('sirolimus');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('leflunomid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('natalizumab');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ekulizumab');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('fingolimod');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('tofacitinib');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('teriflunomid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('apremilast');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('vedolizumab');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('alemtuzumab');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('okrelizumab');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('baricitinib');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('siponimod');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('upadacitinib');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('etanercept');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('infliksimab');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('adalimumab');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('certolizumab pegol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('golimumab');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('baziliksimab');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ustekinumab');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('tocilizumab');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('sekukinumab');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('iksekizumab');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('sarilumab');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('guselkumab');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('risankizumab');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ciklosporin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('takrolimus');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('azatioprin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('lenalidomid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('pirfenidon');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('pomalidomid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('dimetil fumarat');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('indometacin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('diklofenak');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('meloksikam');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ibuprofen');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ketoprofen');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('natrij-aurotiomalat');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('penicilamin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('suksametonij');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('pankuronij');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('vekuronij');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('atrakurij');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('rokuronij');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('C. botulinum toxin tip A-hemaglutinin kompleks');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('clostridium botulinum neurotoksin tip A (150 kD)');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('baklofen');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('tizanidin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('dantrolen');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('alopurinol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('kolhicin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('pamidronat');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('alendronat natrij');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ibandronatna kiselina');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('risedronat natrij');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('zoledronatna kiselina');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('denosumab');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ataluren');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('nusinersen');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('sevofluran');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('tiopental-natrij');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('fentanil');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('alfentanil');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('sufentanil');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('fentanil + droperidol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ketamin-klorid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('etomidat');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('propofol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('dušik-oksidul');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('prokain');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('bupivakain');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('artikain');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ropivakain');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('levobupivakain');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('lidokain + adrenalin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('butanilkain + noradrenalin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('artikain + adrenalin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('kloretil (etil-klorid)');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('morfin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('oksikodon');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('oksikodon + nalokson');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('petidin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('buprenorfin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('tramadol + paracetamol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('tramadol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('tapentadol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('metamizol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('paracetamol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('sumatriptan');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('metilfenobarbital');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('fenobarbiton-natrij');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('fenobarbital');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('primidon');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('fenitoin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('etosuksimid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('klonazepam');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('karbamazepin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('okskarbazepin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('natrij-valproat');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('vigabatrin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('lamotrigin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('topiramat');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('gabapentin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('levetiracetam');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('zonisamid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('pregabalin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('lakozamid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('triheksifenidil');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('biperiden');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('levodopa + karbidopa');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('levodopa + karbidopa + entakapon');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('amantadin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ropinirol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('pramipeksol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('razagilin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('entakapon');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('levomepromazin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('promazin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('flufenazin-dekanoat');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('flufenazin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('perazin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('haloperidol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('haloperidol-dekanoat');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('sertindol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ziprazidon');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('klozapin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('olanzapin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('kvetiapin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('sulpirid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('amisulprid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('litij-karbonat');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('risperidon');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('aripiprazol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('paliperidon');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('diazepam');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('lorazepam');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('klobazam');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('alprazolam');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('meprobamat');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('flurazepam');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('nitrazepam');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('midazolam');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('zolpidem');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('klometiazol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('deksmedetomidin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('klomipramin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('amitriptilin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('maprotilin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('paroksetin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('sertralin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('escitalopram');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('mirtazapin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('venlafaksin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('duloksetin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('modafinil');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('kofein citrat');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('idebenon');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('neostigminij');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('piridostigminij');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('disulfiram');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('metadon');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('buprenorfin+nalokson');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('riluzol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('natrijev oksibat');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('klorokin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('kinin-sulfat');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('pirimetamin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('artemeter');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('prazikvantel');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('mebendazol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('albendazol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('piretrin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('krotamiton (krema)');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('krotamiton (losion)');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('salbutamol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('salmeterol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('formoterol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('indakaterol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('salmeterol + flutikazon');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('budesonid + formoterol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('beklometazon + formoterol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ipratropijev bromid/salbutamol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('beklometazon + formoterol + glikopironij');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('beklometazon');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('budesonid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('flutikazon');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ciklezonid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ipratropij-bromid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('tiotropij bromid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('orciprenalin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('kisik');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('aminofilin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('montelukast');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('omalizumab');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('reslizumab');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('mepolizumab');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('benralizumab');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('dornaze alfa (dezoksiribonukleaza)');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('kodein');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('dimetinden');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('kloropiramin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('tietilperazin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('cetirizin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('loratadin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('feksofenadin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('desloratadin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('surfaktant, prirodni (goveđi)');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('surfaktant, prirodni (svinjski)');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('brimonidin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('karbakol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('acetazolamid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('dorzolamid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('timolol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('timolol + dorzolamid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('latanoprost + timolol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('latanoprost');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('tropikamid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('fenilefrin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('fluorescein');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('hipromeloza');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ranibizumab');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('voretigen neparvovek');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('alergeni za specifičnu imunoterapiju');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('natrij-kalcij-edetat');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('pralidoksim');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('protamin-sulfat');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('nalokson');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('acetilcistein');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('flumazenil');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('sugamadeks');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('idarucizumab');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('deferoksamin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('deferasiroks');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('kalcij-polistirensulfonat (ionski izmjenjivač)');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('sevelamer-karbonat');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('kalcijev acetat + magnezijev subkarbonat teški');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('saharoželjezov (III) oksihidroksid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('mesna (merkaptoetan-sulfonska kiselina)');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('kalcij-folinat');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('metirapon');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('tuberkulin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('protirelin (TRH)');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('alergeni grupni za testiranje');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('alergeni pojedinačni za testiranje');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('dijetetski preparat');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('dijetetski preparati-pripravci bez ili sa smanjenim udjelom fenilalanina');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('glukoza (amp. 37 %)');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('glukoza (amp. 50 %)');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('namirnice za enteralnu primjenu');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('voda redestilirana');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('irigacijske otopine');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('puna krv');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('+ puna krv za autolognu transfuziju');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('puna krv sa smanjenim brojem leukocita');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('svježe smrznuta plazma');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('svježe smrznuta plazma dobivena plazmaferezom');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('+ svježe smrznuta plazma - inaktivacija patogena');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('+ svježe smrznuta plazma dobivena plazmaferezom - inaktivacija patogena');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('+ svježe smrznuta plazma dobivena plazmaferezom sa smanjenim sadržajem krioprecipitata');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('+ svježe smrznuta plazma sa smanjenim brojem leukocita - filtrirana plazma');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('+ svježe smrznuta plazma za autolognu transfuziju');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('koncentrat eritrocita');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('koncentrat eritrocita u hranjivoj otopini');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('koncentrat eritrocita bez sloja leukocita i trombocita');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('koncentrat eritrocita bez sloja leukocita i trombocita, u hranjivoj otopini');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('+ koncentrat eritrocita bez sloja leukocita i trombocita - ozračen');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('+koncentrat eritrocita za autolognu transfuziju');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('koncentrat eritrocita sa smanjenim brojem leukocita');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('koncentrat eritrocita sa smanjenim brojem leukocita, u hranjivoj otopini');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('koncentrat eritocita sa smanjenim brojem leukocita, u hranjivoj otopini - ozračen');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('+ koncentrat eritrocita sa smanjenim brojem leukocita - ozračen');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('koncentrat opranih eritrocita');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('koncentrat opranih eritrocita sa smanjenim brojem leukocita');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('+ koncentrat opranih eritrocita sa smanjenim brojem leukocita - ozračen');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('koncentrat eritrocita u plazmi');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('+ koncentrat eritrocita u plazmi sa smanjenim brijem leukocita - ozračen');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('+ koncentrat eritrocita u plazmi sa smanjenim brojem leukocita');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('koncentrat trombocita dobiven trombaferezom');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('koncentrat trombocita dobiven tromboferezom, sa smanjenim brojem leukocita');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('+ koncentrat trombocita dobiven trombaferezom sa smanjenim brojem leukocita - inaktivacija patogena');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('+ koncentrat trombocita dobiven trombaferezom sa smanjenim brojem leukocita u smanjenom volumenu plazme - inaktivacija patogena');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('+ koncentrat opranih trombocita dobiven trombaferezom sa smanjenim brojem leukocita - inaktivacija patogena');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('+ koncentrat trombocita dobiven trombaferezom sa smanjenim brojem leukocita - ozračen');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('+ koncentrat trombocita dobiven trombaferezom sa smanjenim brojem leukocita u smanjenom volumenu plazme - ozračen');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('+ koncentrat opranih trombocita dobiven trombaferezom sa smanjenim brojem leukocita - ozračen');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('+ koncentrat trombocita dobiven trombaferezom sa smanjenim brojem leukocita u smanjenom volumenu plazme');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('+ koncentrat opranih trombocita sa smanjenim brojem leukocita - trombafereza');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('koncentrat trombocita dobiven tromboferezom u hranjivoj otopini sa smanjenim brojem leukocita');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('+ koncentrat trombocita dobiven trombaferezom u hranjivoj otopini sa smanjenim brojem leukocita - ozračen');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('+ koncentrat trombocita dobiven trombaferezom u hranjivoj otopini sa smanjenim brojem leukocita - inaktivacija patogena');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('+ koncentrat trombocita dobiven trombaferezom u hranjivoj otopini sa smanjenim brojem leukocita u smanjenom volumenu - ozračen');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('+ koncentrat trombocita dobiven trombaferezom u hranjivoj otopini sa smanjenim brojem leukocita u smanjenom volumenu');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('+ koncentrat trombocita dobiven trombaferezom u hranjivoj otopini sa smanjenim brojem leukocita u smanjenom volumenu - inaktivacija patogena');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('koncentrat trombocita');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('koncentrat trombocita-više doza');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('koncentrat trombocita iz sloja leukocita i trombocita');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('koncentrat trombocita iz sloja leukocita i trombocita-više doza');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('+ koncentrat trombocita iz sloja leukocita i trombocita sa smanjenim brojem leukocita pool više doza u smanjenom volumenu plazme - inaktivacija patogena');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('+koncentrat trombocita iz sloja leukocita i trombocita sa smanjenim brojem leukocita pool više doza u smanjenom volumenu plazme - ozračen');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('+ koncentrat trombocita u smanjenom volumenu plazme - 1 doza');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('+ koncentrat trombocita u smanjenom volumenu plazme - više doza');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('+ koncentrat trombocita sa smanjenim brojem leukocita u smanjenom volumenu plazme - više davatelja');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('+koncentrat trombocita iz sloja leukocita i trombocita u hranjivoj otopini sa smanjenim brojem leukocita pool više doza u smanjenom volumenu - ozračen');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('+ koncentrat trombocita iz sloja leukocita i trombocita u hranjivoj otopini sa smanjenim brojem leukocita, pool više doza u smanjenom volumenu');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('koncentrat trombocita sa smanjenim brojem leukocita više davatelja');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('koncentrat trombocita sa smanjenim brojem leukocita');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('+ koncentrat trombocita iz sloja leukocita i trombocita sa smanjenim brojem leukocita pool više doza - inaktivacija patogena');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('+ koncentrat opranih trombocita iz sloja leukocita i trombocita sa smanjenim brojem leukocita pool više doza - inaktivacija patogena');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('+ koncentrat trombocita iz sloja leukocita i trombocita sa smanjenim brojem leukocita pool više davatelja - ozračen');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('+ koncentrat opranih trombocita iz sloja leukocita i trombocita sa smanjenim brojem leukocita pool više doza - ozračen');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('+ koncentrat opranih trombocita sa smanjenim brojem leukocita - više doza');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('koncentrat trombocita iz sloja leukocita i trombocita u hranjivoj otopini sa smanjenim brojem leukocita, pool više doza');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('+ koncentrat trombocita iz sloja leukocita i trombocita u hranjivoj otopini sa smanjenim brojem leukocita pool više doza - inaktivacija patogena');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('+ koncentrat trombocita iz sloja leukocita i trombocita u hranjivoj otopini sa smanjenim brojem leukocita pool više davatelja - ozračen');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('+ koncentrat trombocita iz sloja leukocita i trombocita sa smanjenim brojem leukocita pool više doza u smanjenom volumenu - inaktivacija patogena');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('koncentrat leukocita dobiven leukoforezom');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('koncentrat leukocita');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('koncentrat leukocitia-više doza');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('koncentrat trombocita i leukocita');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('koncentrat trombocita i leukocita-više doza');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('+ koncentrat leukocita i trombocita pool više doza - ozračen');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('+ koncentrat leukocita i trombocita - ozračen');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('krioprecipitat univerzalni-deset doza');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('krioprecipitat liofiliziran iz 1500 ml plazme');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('polivinilalkohol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('gel za ultrazvuk');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('gel za EEG i EKG');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('meglumin joksitalamat+natrij joksitalamat');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('meglumin-amidotrizoat-65%');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('natrijev amidotrizoat + meglumin amidotrizoat');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('joheksol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('joksaglikanska kiselina');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('jopamidol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('jopromid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('joversol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('jodiksanol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('iomeprol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('jobitridol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('jodoksaminska kiselina meglumin-jodoksamat');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('smjesa etilnih estera jodiranih masnih kiselina (lipiodol-ultrafluid)');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('barij-sulfat');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('gadoteratna kiselina');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('gadobenična kiselina');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('gadobutrol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('gadoksetična kiselina');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ioflupan');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('fludeoksiglukoza (18F)');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('radij-223 diklorid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('sterilna gaza');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('komprese');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('zavoj utkani');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('zavoj kaliko utkani');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('zavoj elastični');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('mikropore');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('staničevina');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('vata');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('mikonazol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('rabeprazol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('mebeverin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('otilonijev bromid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('pinaverij bromid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('makrogol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('prukaloprid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('loperamid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('mesalazin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('racekadotril');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('orlistat');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('degludek inzulin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('inzulin degludek + liraglutid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('glikvidon');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('pioglitazon + glimepirid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('sitagliptin + metformin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('alogliptin + pioglitazon');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('saksagliptin + metformin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('linagliptin + metformin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('alogliptin + metformin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('dapagliflozin + metformin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('empagliflozin + metformin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('saksagliptin + dapagliflozin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ertugliflozin + metformin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ertugliflozin + sitagliptin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('akarboza');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('sitagliptin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('saksagliptin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('alogliptin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('linagliptin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('liraglutid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('dapagliflozin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('empagliflozin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ertugliflozin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('alfakalcidol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('klopidogrel + acetilsalicilna kiselina');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('edoksaban');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('željezo III-hidroksi polimaltozat');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('željezo III- proteinsukcinilat');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('dronedaron');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ivabradin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ranolazin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('torasemid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('spironolakton');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('eplerenon');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('sotalol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('bisoprolol + hidroklorotiazid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('nebivolol + hidroklorotiazid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('bisoprolol + amlodipin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('felodipin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('verapamil + trandolapril');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('diltiazem');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('indapamid + amlodipin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('fosinopril');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('trandolapril');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('zofenopril');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('fosinopril + hidroklorotiazid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('zofenopril + hidroklorotiazid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ramipril + felodipin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('bisoprolol + perindopril');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('irbesartan');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('olmesartan medoksomil');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('irbesartan + hidroklorotiazid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('olmesartan + hidroklorotiazid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('olmesartan + amlodipin + hidroklorotiazid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('sakubitril + valsartan');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('etilni esteri omega-3 kiselina');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ezetimib+simvastatin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('fenofibrat + simvastatin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ezetimib + atorvastatin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('rosuvastatin + acetilsalicilatna kiselina');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('atorvastatin + perindopril + amlodipin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('klotrimazol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('izokonazol, diflukortolon');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ciklopiroksolamin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('amorolfin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('naftifinklorid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('nezasićene masne kiseline (C18 : 2)');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('kalcipotriol + betametazon');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('imikvimod');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('mometazon');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('metilprednizolon aceponat');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('fusidatna kiselina + betametazon');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('estradiolbenzoat + prednizolon + salicilna kiselina');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('prednizolon + salicilna kiselina');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('adapalen');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('benzoil peroksid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('klindamicin + benzoilperoksid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('azelatna kiselina');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('izotretinoin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('takrolimus hidrat');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('pimekrolimus');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('nistatin + oksitetraciklin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('neomicin + polimiksin B + nistatin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('nifuratel + nistatin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('bromokriptin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('etinilestradiol + levonorgestrel');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('gestoden + etinilestradiol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('etinilestradiol + drospirenon');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('nomegestrolacetat + estradiol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('etinilestradiol + klormadinon');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('etinilestradiol+dienogest');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('etinilestradiol + dienogest');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('estradiol + dienogest');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('didrogesteron');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('dienogest');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('estradiol + noretisteron');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('drospirenon + estradiol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('estradiol + didrogesteron');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ciproteron-acetat+etinilestradiol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ulipristal acetat');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('propiverin klorid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('dutasterid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('acemetacin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('piroksikam');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('naproksen');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('deksketoprofen');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('celekoksib');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('etorikoksib');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('febuksostat');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('risedronat natrij + kalcij + kolekalciferol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('alendronat natrij + kolekalciferol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('tramadol + deksketoprofen');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('zolmitriptan');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('rizatriptan');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('eletriptan');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('erenumab');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('galkanezumab');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('fremanezumab');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('levodopa + benzerazid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('rotigotin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('oksazepam');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('bromazepam');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('fluoksetin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('citalopram');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('fluvoksamin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('moklobemid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('trazodon');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('bupropion');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('tianeptin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('reboksetin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('agomelatin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('vortioksetin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('donepezil');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('memantin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('betahistin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('tetrabenazin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('ksilometazolin + ipratropij bromid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('flutikazon furoat');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('azelastin hidroklorid + flutikazon propionat');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('flutikazonfuorat + vilanterol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('umeklidinij + vilanterol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('indakaterol + glikopironij');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('aklidinij + formoterol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('tiotropij bromid + olodaterol klorid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('flutikazonfuroat + umeklidinij + vilanterol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('aklidinij (aklidinijev bromid)');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('glikopironij');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('umeklidinij bromid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('teofilin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('roflumilast');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('folkodin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('butamirat');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('levocetirizin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('bilastin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('diklofenak natrij');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('bromfenak');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('tobramicin + deksametazon');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('deksametazon + neomicin + polimiksin B');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('brinzolamid');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('brinzolamid + brimonidin tartarat');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('betaksolol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('brinzolamid + timolol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('tafluprost + timolol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('travoprost + timolol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('bimatoprost + timolol');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('timolol + brimonidin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('bimatoprost');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('travoprost');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('tafluprost');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('azelastin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('olopatadin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('namirnice bez glutena');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('klaritromicin');
INSERT INTO djelotvorna_tvar (naziv_djel_tvar) VALUES('azitromicin');
