INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Zagreb', '10000');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Lučko', '10250');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Hrvatski Leskovac', '10251');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Donji Dragonožec', '10253');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Gornji Stupnik', '10255');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Brezovica', '10257');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Zaprešić', '10290');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Prigorje Brdovečko', '10291');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Šenkovec', '10292');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Dubravica', '10293');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Donja Pušća', '10294');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Kupljenovo', '10295');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Luka', '10296');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Jakovlje', '10297');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Donja Bistra', '10298');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Marija Gorica', '10299');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Ivanić-Grad', '10310');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Posavski Bregi', '10311');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Kloštar Ivanić', '10312');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Graberje Ivaničko', '10313');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Križ', '10314');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Novoselec', '10315');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Lijevi Dubrovčak', '10316');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Vrbovec', '10340');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Lonjica', '10341');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Dubrava', '10342');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Nova Kapela', '10343');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Farkaševac', '10344');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Gradec', '10345');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Preseka', '10346');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Rakovec', '10347');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Sesvete', '10360');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Sesvete-Kraljevec', '10361');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Kašina', '10362');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Belovar', '10363');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Dugo Selo', '10370');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Oborovo', '10372');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Ivanja Reka', '10373');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Sveti Ivan Zelina', '10380');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Bedenica', '10381');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Donja Zelina', '10382');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Komin', '10383');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Velika Mlaka', '10408');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Velika Gorica', '10410');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Orle', '10411');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Donja Lomnica', '10412');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Kravarsko', '10413');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Pokupsko', '10414');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Novo Čiče', '10415');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Buševec', '10417');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Dubranec', '10418');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Vukovina', '10419');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Samobor', '10430');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Sveta Nedjelja', '10431');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Bregana', '10432');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Strmec Samoborski', '10434');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Sveti Martin pod Okićem', '10435');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Rakov Potok', '10436');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Bestovje', '10437');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Jastrebarsko', '10450');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Pisarovina', '10451');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Gorica Svetojanska', '10453');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Krašić', '10454');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Kostanjevac', '10455');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Kalje', '10456');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Sošice', '10457');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Dubrovnik', '20000');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Topolo', '20205');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Mlini', '20207');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Cavtat', '20210');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Čilipi', '20213');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Gruda', '20215');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Dubravka', '20216');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Pridvorje', '20217');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Pločice', '20218');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Koločep', '20221');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Lopud', '20222');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Šipanjska Luka', '20223');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Maranovići', '20224');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Babino Polje', '20225');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Goveđari', '20226');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Ston', '20230');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Doli', '20231');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Slano', '20232');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Trsteno', '20233');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Orašac', '20234');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Zaton Veliki', '20235');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Mokošica', '20236');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Trpanj', '20240');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Oskorušno', '20242');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Kuna', '20243');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Potomje', '20244');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Trstenik', '20245');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Janjina', '20246');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Žuljana', '20247');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Putniković', '20248');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Orebić', '20250');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Korčula', '20260');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Lumbarda', '20263');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Račišće', '20264');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Kućište', '20267');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Lovište', '20269');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Vela Luka', '20270');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Blato', '20271');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Smokvica', '20272');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Čara', '20273');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Pupnat', '20274');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Žrnovo', '20275');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Nova Sela', '20278');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Lastovo', '20290');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Ploče', '20340');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Kula Norinska', '20341');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Otrić Seoci', '20342');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Rogotin', '20343');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Komin (Dalmacija)', '20344');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Staševica', '20345');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Metković', '20350');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Vid', '20352');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Mlinište', '20353');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Opuzen', '20355');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Klek', '20356');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Blace', '20357');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Split', '21000');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Prgomet', '21201');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Lećevica', '21202');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Donji Muć', '21203');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Dugopolje', '21204');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Donji Dolac', '21205');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Donje Ogorje', '21206');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Kostanje', '21207');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Kučiće', '21208');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Mravince', '21209');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Solin', '21210');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Kaštel Sućurac', '21212');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Kaštel Gomilica', '21213');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Kaštel Kambelovac', '21214');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Kaštel Lukšić', '21215');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Kaštel Stari', '21216');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Seget Donji', '21218');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Trogir', '21220');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Marina', '21222');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Okrug Gornji', '21223');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Slatine', '21224');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Drvenik Veliki', '21225');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Vinišće', '21226');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Primorski Dolac', '21227');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Blizna Donja', '21228');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Crivac', '21229');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Sinj', '21230');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Klis', '21231');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Dicmo', '21232');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Hrvace', '21233');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Otišić', '21235');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Vrlika', '21236');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Otok (Dalmacija)', '21238');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Trilj', '21240');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Obrovac Sinjski', '21241');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Grab', '21242');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Ugljane', '21243');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Cista Velika', '21244');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Tijarica', '21245');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Aržano', '21246');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Neorić', '21247');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Šestanovac', '21250');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Žrnovnica', '21251');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Tugare', '21252');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Gata', '21253');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Blato na Cetini', '21254');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Zadvarje', '21255');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Cista Provo', '21256');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Lovreć', '21257');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Imotski', '21260');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Runović', '21261');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Kamenmost', '21262');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Krivodol', '21263');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Donji Proložac', '21264');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Studenci', '21265');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Zmijavci', '21266');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Ričice', '21267');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Zagvozd', '21270');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Grabovac', '21271');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Slivno', '21272');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Župa', '21273');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Dragljane', '21275');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Vrgorac', '21276');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Veliki Prolog', '21277');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Srinjine', '21292');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Makarska', '21300');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Omiš', '21310');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Stobreč', '21311');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Podstrana', '21312');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Jesenice', '21314');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Dugi Rat', '21315');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Lokva Rogoznica', '21317');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Mimice', '21318');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Baška Voda', '21320');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Brela', '21322');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Tučepi', '21325');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Podgora', '21327');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Drašnice', '21328');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Igrane', '21329');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Gradac', '21330');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Drvenik', '21333');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Zaostrog', '21334');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Podaca', '21335');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Supetar', '21400');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Sutivan', '21403');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Ložišća', '21404');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Milna', '21405');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Postira', '21410');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Pučišća', '21412');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Povlja', '21413');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Bol', '21420');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Nerežišća', '21423');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Pražnica', '21424');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Selca', '21425');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Sumartin', '21426');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Grohote', '21430');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Stomorska', '21432');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Hvar', '21450');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Brusje', '21454');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Stari Grad', '21460');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Vrbanj', '21462');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Vrboska', '21463');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Jelsa', '21465');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Zastražišće', '21466');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Gdinj', '21467');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Bogomolje', '21468');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Sućuraj', '21469');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Vis', '21480');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Podšpilje', '21483');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Komiža', '21485');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Šibenik', '22000');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Šibenik-Brodarica', '22010');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Šibenik-Ražine', '22020');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Šibenik-Zablaće', '22030');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Primošten', '22202');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Rogoznica', '22203');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Široke', '22204');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Perković', '22205');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Boraja', '22206');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Vodice', '22211');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Tribunj', '22212');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Pirovac', '22213');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Čista Velika', '22214');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Zaton', '22215');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Lozovac', '22221');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Skradin', '22222');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Bribir(kod Skradina)', '22223');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Zlarin', '22232');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Prvić Luka', '22233');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Prvić Šepurine', '22234');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Kaprije', '22235');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Žirje', '22236');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Tisno', '22240');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Jezera', '22242');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Murter', '22243');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Betina', '22244');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Knin', '22300');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Golubić', '22301');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Polača/kod Knina/', '22302');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Oklaj', '22303');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Radučić', '22304');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Kistanje', '22305');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Ervenik', '22306');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Mokro Polje', '22307');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Kijevo', '22310');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Strmica', '22311');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Kosovo/Zvjerinac/', '22312');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Plavno', '22317');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Pađene', '22318');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Đevrske', '22319');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Drniš', '22320');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Siverić', '22321');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Ružić', '22322');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Unešić', '22323');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Drinovci', '22324');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Zadar', '23000');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Bibinje', '23205');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Sukošan', '23206');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Sveti Filip i Jakov', '23207');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Biograd na moru', '23210');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Pakoštane', '23211');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Tkon', '23212');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Zemunik', '23222');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Škabrnja', '23223');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Pridraga', '23226');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Petrčane', '23231');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Nin', '23232');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Privlaka (Dalmacija)', '23233');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Vir', '23234');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Vrsi', '23235');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Poličnik', '23241');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Posedarje', '23242');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Starigrad Paklenica', '23244');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Tribanj', '23245');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Vinjerac', '23247');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Ražanac', '23248');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Povljana', '23249');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Pag', '23250');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Kolan', '23251');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Pašman', '23262');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Ždrelac', '23263');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Neviđane', '23264');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Kukljica', '23271');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Kali', '23272');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Preko', '23273');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Lukoran', '23274');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Ugljan', '23275');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Sali', '23281');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Žman', '23282');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Rava', '23283');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Veli Iž', '23284');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Brbinj', '23285');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Božava', '23286');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Veli Rat', '23287');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Sestrunj', '23291');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Molat', '23292');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Ist', '23293');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Premuda', '23294');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Silba', '23295');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Olib', '23296');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Novigrad (Dalmacija)', '23312');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Benkovac', '23420');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Bjelina', '23421');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Stankovci', '23422');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Polača', '23423');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Smilčić', '23424');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Gračac', '23440');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Bruvno', '23441');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Otrić', '23442');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Zrmanja', '23443');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Srb', '23445');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Kaldrma', '23446');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Obrovac', '23450');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Žegar', '23451');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Karin', '23452');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Osijek', '31000');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Bijelo Brdo', '31204');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Aljmaš', '31205');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Erdut', '31206');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Tenja', '31207');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Petrijevci', '31208');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Laslovo', '31214');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Ernestinovo', '31215');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Antunovac', '31216');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Višnjevac', '31220');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Josipovac', '31221');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Bizovac', '31222');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Brođanci', '31223');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Koška', '31224');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Breznica Našička', '31225');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Dalj', '31226');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Zelčin', '31227');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Beli Manastir', '31300');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Branjin Vrh', '31301');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Kneževo', '31302');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Popovac', '31303');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Duboševica', '31304');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Draž', '31305');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Batina', '31306');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Zmajevac', '31307');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Suza', '31308');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Kneževi Vinogradi', '31309');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Karanac', '31315');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Petlovac', '31321');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Baranjsko Petrovo Selo', '31322');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Bolman', '31323');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Jagodnjak', '31324');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Čeminac', '31325');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Darda', '31326');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Bilje', '31327');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Lug', '31328');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Đakovo', '31400');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Viškovci', '31401');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Semeljci', '31402');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Vuka', '31403');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Vladislavci', '31404');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Strizivojna', '31410');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Trnava', '31411');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Selci Đakovački', '31415');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Levanjska Varoš', '31416');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Piškorevci', '31417');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Drenje', '31418');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Satnica Đakovačka', '31421');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Gorjani', '31422');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Bračevci', '31423');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Punitovci', '31424');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Čepin', '31431');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Budimci', '31432');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Podgorač', '31433');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Našice', '31500');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Đurđenovac', '31511');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Feričanci', '31512');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Donja Motičina', '31513');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Podravska Moslavina', '31530');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Viljevo', '31531');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Donji Miholjac', '31540');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Magadenovac', '31542');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Miholjački Poreč', '31543');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Valpovo', '31550');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Belišće', '31551');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Podgajci Podravski', '31552');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Črnkovci', '31553');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Gat', '31554');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Marijanci', '31555');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Vukovar', '32000');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Vukovar', '32010');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Vinkovci', '32100');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Ostrovo', '32211');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Gaboš', '32212');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Markušica', '32213');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Tordinci', '32214');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Nuštar', '32221');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Bršadin', '32222');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Trpinja', '32224');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Bobota', '32225');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Borovo', '32227');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Petrovci', '32229');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Sotin', '32232');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Opatovac', '32233');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Šarengrad', '32234');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Bapska', '32235');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Ilok', '32236');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Lovas', '32237');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Čakovci', '32238');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Negoslavci', '32239');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Stari Jankovci', '32241');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Slakovci', '32242');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Orolik', '32243');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Đeletovci', '32244');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Nijemci', '32245');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Lipovac', '32246');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Banovci', '32247');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Ilača', '32248');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Tovarnik', '32249');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Privlaka', '32251');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Otok', '32252');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Komletinci', '32253');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Vrbanja', '32254');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Soljani', '32255');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Strošinci', '32256');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Drenovci', '32257');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Posavski Podgajci', '32258');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Gunja', '32260');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Rajevo Selo', '32261');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Račinovci', '32262');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Đurići', '32263');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Županja', '32270');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Rokovci Andrijaševci', '32271');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Cerna', '32272');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Gradište', '32273');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Štitar', '32274');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Bošnjaci', '32275');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Babina Greda', '32276');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Jarmina', '32280');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Ivankovo', '32281');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Retkovci', '32282');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Vođinci', '32283');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Stari Mikanovci', '32284');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Virovitica', '33000');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Špišić Bukovica', '33404');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Pitomača', '33405');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Lukač', '33406');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Gornje Bazje', '33407');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Suhopolje', '33410');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Gradina', '33411');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Cabuna', '33412');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Crnac', '33507');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Zdenci', '33513');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Čačinci', '33514');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Orahovica', '33515');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Slatinski Drenovac', '33516');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Mikleuš', '33517');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Nova Bukovica', '33518');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Slatina', '33520');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Ćeralije', '33521');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Voćin', '33522');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Čađavica', '33523');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Sopje', '33525');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Pivnica Slavonska', '33533');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Požega', '34000');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Jakšić', '34308');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Pleternica', '34310');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Kuzmica', '34311');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Sesvete (kod Požege)', '34312');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Ratkovica', '34315');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Orljavac', '34320');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Brestovac', '34322');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Velika', '34330');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Kaptol', '34334');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Vetovo', '34335');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Kutjevo', '34340');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Bektež', '34343');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Čaglin', '34350');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Poljana', '34543');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Pakrac', '34550');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Lipik', '34551');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Badljevina', '34552');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Bučje', '34553');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Slavonski Brod', '35000');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Slavonski Brod', '35105');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Slavonski Brod', '35106');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Podvinje', '35107');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Podcrkavlje', '35201');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Gornja Vrba', '35207');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Ruščica', '35208');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Bukovlje', '35209');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Vrpolje', '35210');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Trnjani', '35211');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Garčin', '35212');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Oprisavci', '35213');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Donji Andrijevci', '35214');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Svilaj', '35215');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Prnjavor', '35216');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Slavonski Šamac', '35220');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Velika Kopanica', '35221');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Gundinci', '35222');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Sikirevci', '35224');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Oriovac', '35250');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Sibinj', '35252');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Brodski Stupnik', '35253');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Bebrina', '35254');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Slavonski Kobaš', '35255');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Lužani', '35257');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Nova Gradiška', '35400');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Rešetari', '35403');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Cernik', '35404');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Nova Kapela', '35410');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Vrbova', '35414');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Staro Petrovo Selo', '35420');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Zapolje', '35422');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Vrbje', '35423');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Orubica', '35424');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Davor', '35425');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Dragalić', '35428');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Gornji Bogićevci', '35429');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Okučani', '35430');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Medari', '35432');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Stara Gradiška', '35435');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Čakovec', '40000');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Nedelišče', '40305');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Macinec', '40306');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Lopatinec', '40311');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Štrigova', '40312');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Sveti Martin na Muri', '40313');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Selnica', '40314');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Mursko Središče', '40315');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Vratišinec', '40316');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Podturen', '40317');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Dekanovec', '40318');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Belica', '40319');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Donji Kraljevec', '40320');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Mala Subotica', '40321');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Orehovica', '40322');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Prelog', '40323');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Goričan', '40324');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Draškovec', '40325');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Sveta Marija', '40326');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Donji Vidovec', '40327');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Donja Dubrava', '40328');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Kotoriba', '40329');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Varaždin', '42000');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Beretinec', '42201');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Trnovec Bartolovečki', '42202');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Jalžabet', '42203');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Turčin', '42204');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Vidovec', '42205');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Petrijanec', '42206');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Vinica', '42207');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Cestica', '42208');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Sračinec', '42209');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Sveti Ilija', '42214');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Novi Marof', '42220');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Ljubeščica', '42222');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Varaždinske Toplice', '42223');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Visoko', '42224');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Breznički Hum', '42225');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Bisag', '42226');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Ludbreg', '42230');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Mali Bukovec', '42231');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Donji Martijanec', '42232');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Sveti Đurđ', '42233');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Ivanec', '42240');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Radovan', '42242');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Maruševec', '42243');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Klenovnik', '42244');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Donja Voća', '42245');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Lepoglava', '42250');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Bednja', '42253');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Trakošćan', '42254');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Donja Višnjica', '42255');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Bjelovar', '43000');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Zrinski Topolovac', '43202');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Kapela', '43203');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Predavac', '43211');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Rovišće', '43212');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Veliko Trojstvo', '43226');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Šandrovac', '43227');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Ivanska', '43231');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Berek', '43232');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Trnovitički Popovac', '43233');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Čazma', '43240');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Gornji Draganec', '43245');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Štefanje', '43246');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Narta', '43247');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Gudovac', '43251');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Prgomelje', '43252');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Veliki Grđevac', '43270');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Velika Pisanica', '43271');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Nova Rača', '43272');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Bulinac', '43273');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Severin', '43274');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Garešnica', '43280');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Veliko Vukovje', '43282');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Kaniška Iva', '43283');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Hercegovac', '43284');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Velika Trnovitica', '43285');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Grubišno Polje', '43290');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Veliki Zdenci', '43293');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Daruvar', '43500');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Ivanovo Selo', '43504');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Končanica', '43505');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Dežanovac', '43506');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Uljanik', '43507');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Veliki Bastaji', '43531');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Đulovac', '43532');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Sirač', '43541');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Sisak', '44000');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Sisak-Caprag', '44010');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Martinska Ves', '44201');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Topolovac', '44202');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Gušće', '44203');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Jabukovac', '44204');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Donja Bačuga', '44205');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Sunja', '44210');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Blinjski Kut', '44211');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Mala Gradusa', '44212');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Kratečko', '44213');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Bobovac', '44214');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Staza', '44221');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Šaš', '44222');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Blinja', '44231');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Petrinja', '44250');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Gora', '44251');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Mošćenica', '44253');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Letovanić', '44271');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Lekenik', '44272');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Sela', '44273');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Velika Ludina', '44316');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Popovača', '44317');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Voloder', '44318');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Kutina', '44320');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Banova Jaruga', '44321');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Lipovljani', '44322');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Rajić', '44323');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Jasenovac', '44324');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Krapje', '44325');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Novska', '44330');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Glina', '44400');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Hajtić', '44401');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Mali Obljaj', '44402');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Maja', '44403');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Gornji Klasnić', '44404');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Mali Gradac', '44405');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Vlahović', '44406');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Gvozd', '44410');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Stankovac', '44412');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Bović', '44414');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Topusko', '44415');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Gornja Bučica', '44425');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Hrvatska Kostajnica', '44430');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Donji Kukuruzari', '44431');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Mečenčani', '44432');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Majur', '44433');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Graboštani', '44434');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Divuša', '44435');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Rujevac', '44437');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Dvor', '44440');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Brđani Šamarički', '44441');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Donji Žirovac', '44443');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Hrvatska Dubica', '44450');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Karlovac', '47000');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Draganići', '47201');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Rečica', '47203');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Šišljavić', '47204');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Vukmanić', '47205');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Lasinja', '47206');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Utinja', '47211');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Skakavac', '47212');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Sjeničak Lasinjski', '47213');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Vojnić', '47220');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Krstinja', '47221');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Cetingrad', '47222');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Slunj', '47240');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Tušilović', '47241');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Krnjak', '47242');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Veljun', '47243');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Primišlje', '47244');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Rakovica', '47245');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Drežnik Grad', '47246');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Duga Resa', '47250');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Bosiljevo', '47251');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Barilović', '47252');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Perjasica', '47253');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Zvečaj', '47261');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Generalski Stol', '47262');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Gornje Dubrave', '47263');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Tounj', '47264');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Netretić', '47271');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Ribnik', '47272');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Srednje Prilišće', '47273');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Žakanje', '47276');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Ozalj', '47280');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Mali Erjavec', '47281');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Kamanje', '47282');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Vivodina', '47283');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Kašt', '47284');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Radatovići', '47285');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Mahično', '47286');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Ogulin', '47300');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Oštarije', '47302');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Josipdol', '47303');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Plaški', '47304');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Lička Jesenica', '47305');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Saborsko', '47306');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Gornje Zagorje', '47307');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Drežnica', '47313');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Jasenak', '47314');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Koprivnica', '48000');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Cirkvena', '48213');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Sveti Ivan Žabno', '48214');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Križevci', '48260');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Carevdar', '48263');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Kloštar Vojakovački', '48264');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Raven', '48265');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Orehovec', '48267');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Gornja Rijeka', '48268');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Kalnik', '48269');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Reka', '48305');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Sokolovac', '48306');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Kunovec', '48311');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Rasinja', '48312');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Koprivnički Ivanec', '48314');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Đelekovec', '48316');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Legrad', '48317');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Peteranec', '48321');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Drnje', '48322');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Hlebine', '48323');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Koprivnički Bregi', '48324');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Novigrad Podravski', '48325');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Virje', '48326');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Molve', '48327');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Gola', '48331');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Ždala', '48332');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Đurđevac', '48350');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Novo Virje', '48355');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Ferdinandovac', '48356');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Kalinovac', '48361');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Kloštar Podravski', '48362');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Podravske Sesvete', '48363');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Krapina', '49000');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Zabok', '49210');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Veliko Trgovišće', '49214');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Tuhelj', '49215');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Desinić', '49216');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Krapinske Toplice', '49217');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Pregrada', '49218');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Bedekovčina', '49221');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Poznanovec', '49222');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Sveti Križ Začretje', '49223');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Lepajci', '49224');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Đurmanec', '49225');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Brestovec Orehovički', '49228');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Hum na Sutli', '49231');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Radoboj', '49232');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Gornje Jesenje', '49233');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Petrovsko', '49234');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Donja Stubica', '49240');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Oroslavje', '49243');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Stubičke Toplice', '49244');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Gornja Stubica', '49245');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Marija Bistrica', '49246');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Zlatar Bistrica', '49247');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Zlatar', '49250');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Mače', '49251');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Mihovljan', '49252');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Lobor', '49253');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Belec', '49254');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Novi Golubovec', '49255');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Konjščina', '49282');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Hraščina-Trgovišće', '49283');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Budinšćina', '49284');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Klanjec', '49290');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Kraljevec na Sutli', '49294');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Kumrovec', '49295');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Zagorska Sela', '49296');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Rijeka', '51000');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Matulji', '51211');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Vele Mune', '51212');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Jurdani', '51213');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Šapjane', '51214');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Kastav', '51215');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Viškovo', '51216');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Klana', '51217');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Dražice', '51218');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Čavle', '51219');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Kostrena', '51221');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Bakar', '51222');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Škrljevo', '51223');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Krasica', '51224');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Praputnjak', '51225');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Hreljin', '51226');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Križišće', '51241');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Drivenik', '51242');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Tribalj', '51243');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Grižane', '51244');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Novi Vinodolski', '51250');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Ledenice', '51251');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Klenovica', '51252');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Bribir', '51253');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Crikvenica', '51260');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Bakarac', '51261');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Kraljevica', '51262');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Šmrika', '51263');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Jadranovo', '51264');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Dramalj', '51265');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Selce', '51266');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Rab', '51280');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Lopar', '51281');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Delnice', '51300');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Brod na Kupi', '51301');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Kuželj', '51302');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Plešce', '51303');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Gerovo', '51304');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Tršće', '51305');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Čabar', '51306');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Prezid', '51307');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Skrad', '51311');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Brod Moravice', '51312');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Kupjak', '51313');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Ravna Gora', '51314');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Mrkopalj', '51315');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Lokve', '51316');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Crni Lug', '51317');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Vrata', '51321');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Fužine', '51322');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Lič', '51323');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Zlobin', '51324');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Moravice', '51325');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Vrbovsko', '51326');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Gomirje', '51327');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Lukovdol', '51328');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Severin na Kupi', '51329');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Opatija', '51410');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Ičići', '51414');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Lovran', '51415');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Mošćenička Draga', '51417');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Brseč', '51418');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Krk', '51500');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Malinska', '51511');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Njivice', '51512');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Omišalj', '51513');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Dobrinj', '51514');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Šilo', '51515');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Vrbnik', '51516');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Kornić', '51517');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Punat', '51521');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Draga Bašćanska', '51522');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Baška', '51523');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Mali Lošinj', '51550');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Veli Lošinj', '51551');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Ilovik', '51552');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Nerezine', '51554');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Belej', '51555');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Martinšćica', '51556');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Cres', '51557');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Beli', '51559');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Susak', '51561');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Unije', '51562');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Ćunski', '51564');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Pazin', '52000');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Pula', '52100');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Medulin', '52203');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Marčana', '52206');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Barban', '52207');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Krnica', '52208');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Rovinj (Rovigno)', '52210');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Bale (Valle)', '52211');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Fažana', '52212');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Vodnjan (Dignano)', '52215');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Galižana (Gallesano)', '52216');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Labin', '52220');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Rabac', '52221');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Koromačno', '52222');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Raša', '52223');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Trget', '52224');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Nedešćina', '52231');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Kršan', '52232');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Šušnjevica', '52233');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Plomin', '52234');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Pićan', '52332');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Podpićan', '52333');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Žminj', '52341');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Svetvinčenat', '52342');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Kanfanar', '52352');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Cerovlje', '52402');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Gračišće', '52403');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Sveti Petar u šumi', '52404');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Buzet', '52420');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Lanišće', '52422');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Karojba', '52423');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Motovun', '52424');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Roč', '52425');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Lupoglav', '52426');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Livade', '52427');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Oprtalj (Portole)', '52428');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Grožnjan (Grisignana)', '52429');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Boljun', '52434');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Poreč', '52440');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Tinjan', '52444');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Baderna', '52445');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Nova Vas', '52446');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Vižinada', '52447');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Sveti Lovreč', '52448');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Červar Porat', '52449');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Vrsar', '52450');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Funtana', '52452');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Buje (Buie)', '52460');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Momjan (Momiano)', '52462');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Višnjan', '52463');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Kaštelir', '52464');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Tar', '52465');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Novigrad (Cittanova)', '52466');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Umag (Umago)', '52470');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Brtonigla (Verteneglio)', '52474');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Savudrija (Salvore)', '52475');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Gospić', '53000');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Lički Osik', '53201');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Perušić', '53202');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Kosinj', '53203');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Medak', '53205');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Brušane', '53206');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Smiljan', '53211');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Klanac', '53212');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Donje Pazarište', '53213');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Otočac', '53220');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Škare', '53221');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Dabar', '53222');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Vrhovine', '53223');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Ličko Lešće', '53224');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Švica', '53225');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Kompolje', '53226');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Korenica', '53230');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Plitvička Jezera', '53231');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Ličko Petrovo Selo', '53233');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Udbina', '53234');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Bunić', '53235');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Podlapača', '53236');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Lovinac', '53244');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Donji Lapac', '53250');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Nebljusi', '53251');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Doljani', '53252');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Brinje', '53260');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Križpolje', '53261');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Jezerane', '53262');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Senj', '53270');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Krivi Put', '53271');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Vratnik', '53273');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Krasno', '53274');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Sveti Juraj', '53284');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Jablanac', '53287');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Karlobag', '53288');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Lukovo Šugarje', '53289');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Novalja', '53291');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Lun', '53294');
INSERT INTO Mjesto (naziv_mjesto, postanski_broj) VALUES('Zubovići', '53296');